# Generated by Django 5.1.1 on 2026-08-23 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MtEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=765)),
                ('slug', models.SlugField(max_length=765)),
                ('published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('preview_image', models.URLField(blank=True, max_length=765)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
                'permissions': [('publish_mtentry', 'Can publish entries')],
            },
        ),
        migrations.CreateModel(
            name='MtComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.CharField(blank=True, max_length=381)),
                ('ip', models.CharField(default='127.0.0.1', max_length=150)),
                ('text', models.TextField()),
                ('url', models.CharField(blank=True, max_length=765)),
                ('visible', models.BooleanField(default=False)),
                ('mt_author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='write.mtcomment')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='write.mtentry')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
